### PR TITLE
Initial db Configuration and Entity Class Creation

### PR DESCRIPTION
**Pull request by bharathtakkalki**
-The required changes to connect and create db and tables is done.

-The entity classes are cretaed as per the schema given.

-The Entity class files created are QuestionEntity,AnswerEntity,UsersEntity,UserAuthEntity.

### CODE REVIEW

**Comment by SonaliBhagwatkar** [comment]
Review request I am able to view

**Review by SonaliBhagwatkar — COMMENTED** [review]
Hello I got it

**Review by SonaliBhagwatkar — APPROVED** [review]

**Review by PearlDsilva — APPROVED** [review]
Looks good

**Review by Pearl1594 — APPROVED** [review]

**Review by MeAmatuer — COMMENTED** [review]
Looks Good.

**Pull request merged**
